[package]
name = "algorithmes-plus-simple-avec-dessin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="binary-search"
path="src/binary-search/bin.rs"

[dependencies]
